## Q1. What is a database? Differentiate between SQL and NoSQL databases.

SQL is the programming language used to interface with relational databases. (Relational databases model data as records in rows and tables with logical links between them). NoSQL is a class of DBMs that are non-relational and generally do not use SQL.

SQL	
1. RELATIONAL DATABASE MANAGEMENT SYSTEM (RDBMS)	
2. These databases have fixed or static or predefined schema	
3. These databases are not suited for hierarchical data storage.
4. These databases are best suited for complex queries	These databases are not so good for complex queries
5. Vertically Scalable	
6. Follows ACID property

NoSQL
1. Non-relational or distributed database system.
2. They have dynamic schema These databases are not suited for hierarchical data storage.	These databases are best suited for hierarchical data storage.
3. Horizontally scalable
4. Follows CAP(consistency, availability, partition tolerance)

## Q2. What is DDL? Explain why CREATE, DROP, ALTER, and TRUNCATE are used with an example.

DDL statements are similar to a computer programming language for defining data structures, especially database schemas. Common examples of DDL statements include CREATE, ALTER, and DROP.

1. DROP :
DROP is a DDL(Data Definition Language) command and is used to remove table definition and indexes, data, constraints, triggers etc for that table. Performance-wise the DROP command is quick to perform but slower than TRUNCATE because it gives rise to complications. Unlike DELETE we can’t rollback the data after using the DROP command. In the DROP command, table space is freed from memory because it permanently delete table as well as all its contents.

2. TRUNCATE :
TRUNCATE is a DDL(Data Definition Language) command. It is used to delete all the tuples from the table. Like the DROP command, the TRUNCATE command also does not contain a WHERE clause. The TRUNCATE command is faster than both the DROP and the DELETE command. Like the DROP command we also can’t rollback the data after using the this command.

## Q3. What is DML? Explain INSERT, UPDATE, and DELETE with an example.


DML is Data Manipulation Language which is used to manipulate data itself. For example: insert, update, delete are instructions in SQL. It stands for Data Definition Language

The SQL INSERT, UPDATE, and DELETE commands enable SQL users to manipulate and modify data:

1. The INSERT statement introduces new rows into an existing table.
2. The DELETE statement removes a row or combination of rows from a table.
3. The UPDATE statement enables users to update a row or group of rows in a table.

## Q4. What is DQL? Explain SELECT with an example.

What is explain SELECT in SQL?
The EXPLAIN keyword is used throughout various SQL databases and provides information about how your SQL database executes a query. In MySQL, EXPLAIN can be used in front of a query beginning with SELECT , INSERT , DELETE , REPLACE , and UPDATE .

 Q5. Explain Primary Key and Foreign Key.

Primary Key: A primary key is used to ensure that data in the specific column is unique. A column cannot have NULL values. It is either an existing table column or a column that is specifically generated by the database according to a defined sequence. 

Example: Refer the figure – 
STUD_NO, as well as STUD_PHONE both, are candidate keys for relation STUDENT but STUD_NO can be chosen as the primary key (only one out of many candidate keys). 

Foreign Key: 
A foreign key is a column or group of columns in a relational database table that provides a link between data in two tables. It is a column (or columns) that references a column (most often the primary key) of another table. 

Example: Refer the figure – 
STUD_NO in STUDENT_COURSE is a foreign key to STUD_NO in STUDENT relation.

## Q6. Write a python code to connect MySQL to python. Explain the cursor() and execute() method.

In [ ]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="abc",
  password="password"
)
print(mydb)
mycursor = mydb.cursor()
mycursor.execute("SHOW DATABASES")
for x in mycursor:
  print(x)

A cursor keeps track of the position in the result set, and allows you to perform multiple operations row by row against a result set, with or without returning to the original table. In other words, cursors conceptually return a result set based on tables within the databases.

## Q7. Give the order of execution of SQL clauses in an SQL query.

In [ ]:
https://cdn.sisense.com/wp-content/uploads/image-1-order-blog.png